export const UNAUTHORIZED = "UNAUTHORIZED";
export const IS_AUTHENTICATE = "IS_AUTHENTICATE";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const TYPE_GET_DATA = "TYPE_GET_DATA";
export const TYPE_POST_DATA = "TYPE_POST_DATA";
export const SET_IS_AUTH_DATA = "SET_IS_AUTH_DATA";